# Generated by Django 4.0.2 on 2022-02-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='username', max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='username', max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for Soft Delete')),
                ('loan_date', models.DateField()),
                ('release_date', models.DateField()),
                ('principal', models.IntegerField(help_text='Principal', max_length=1000)),
                ('total', models.FloatField()),
                ('rate', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
